name: "Deploy Hola mundo"

on:
  push:
    branches: ["main"]

jobs:
    deploy-prueba:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Hacer pull del codigo"
        - run: echo "Correr migracion"
        - run: echo "generar binario"
        - run: echo "publicar version"